const PaintingsDatabase = [
    {   id: 1,
        name: 'Mona Lisa',
        img: '/imgs/paintings/mona-lisa.jpg',
        frameImg: '/imgs/frames/mona-lisa-frame.jpg',
        frameHueBkgrd: 'rgba(229, 202, 174, 0)',
        sizing: {
            imgRelativeSize: 0.8,
            imgWidth: 536,
            imgHeight: 800,
            frameToArtPct: 0.10,
            frameToMatPct: 0
        },
        otherName: ['Monna Lisa', 'La Gioconda', 'La Joconde'],
        artist: 'Leonardo Da Vinci',
        origin: 'Italy',
        dimensions: '77 cm × 53 cm',
        location: 'The Louvre Museum, Paris',
        years: '1503–1506, perhaps continuing until 1517',
        medium: 'Oil on poplar panel',
        link: 'https://en.wikipedia.org/wiki/Mona_Lisa',
        artistLink: 'https://en.wikipedia.org/wiki/Leonardo_da_Vinci'
    },
    {   id: 2,
        name: 'The Great Wave off Kanagawa',
        img: '/imgs/paintings/the-great-wave-of-kanagawa.jpg',
        frameImg: '/imgs/frames/the-great-wave-of-kanagawa-frame.png',
        frameHueBkgrd: '#e5caae',
        sizing: {
            imgRelativeSize: 0.8, 
            imgWidth: 800, 
            imgHeight: 538, 
            frameToArtPct: 0.10, 
            frameToMatPct: 0.025   
        },
        otherName: ['神奈川沖浪裏', 'Under the Wave off Kanagawa', 'The Great Wave', 'The Wave'],
        artist: 'Katsushika Hokusai',
        origin: 'Japan',
        dimensions:'25.7 cm × 37.8 cm',
        location: 'Numerous',
        years: '1829–1833',
        medium: 'woodblock print',
        link: 'https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa',
        artistLink: 'https://en.wikipedia.org/wiki/Hokusai'
    },
    {   id: 3,
        name: 'The Starry Night',
        img: 'TO DEFINE',
        frameImg: 'TO DEFINE',
        otherName: [],
        artist: '	Vincent Van Gogh',
        origin: 'Holland',
        dimensions:'73.7 cm × 92.1 cm',
        location:'Museum of Modern Art, New York',
        years: '1889',
        medium: 'Oil on Canvas',
        link: 'https://en.wikipedia.org/wiki/The_Starry_Night',
        artistLink: 'https://en.wikipedia.org/wiki/Vincent_van_Gogh'
    },
    {   id: 4,
        name: 'The Raft of the Medusa',
        img: 'TO DEFINE',
        frameImg: 'TO DEFINE',
        otherName: ['Le Radeau de la Méduse', 'Scène de Naufrage'],
        artist: '	Théodore Géricault',
        origin: 'France',
        dimensions:'490 cm × 716 cm',
        location: 'The Louvre Museum, Paris',
        years: '1818-1819',
        medium: 'Oil on Canvas',
        link: 'https://en.wikipedia.org/wiki/The_Raft_of_the_Medusa',
        artistLink: 'https://en.wikipedia.org/wiki/Th%C3%A9odore_G%C3%A9ricault'
    },
    {   id: 5,
        name: 'American Gothic',
        img: 'TO DEFINE',
        frameImg: 'TO DEFINE',
        otherName: ['American Gothic House'],
        artist: 'Grant Wood',
        origin: 'USA',
        dimensions:'78 cm × 65.3 cm',
        location: 'Art Institute, Chicago',
        years: '1930',
        medium: 'Oil on Beaverboard',
        link: 'https://en.wikipedia.org/wiki/American_Gothic',
        artistLink: 'https://en.wikipedia.org/wiki/Grant_Wood'
    }
]

export { PaintingsDatabase }